TypeOFAPI = Banking

LoginEndPoint=https://qnajbqxmpbmndnwdqswq.supabase.co/auth/v1/token?grant_type=password

#Generally we can mention the browser name, browser details, close browsers etc..

#We can also maintain the DB Details
